package com.example.compose1.model

import com.example.compose1.R

data class Employee(var img: Int, var name: String, var designation: String)

fun getEmployees(): List<Employee> {
    return listOf(
        Employee(img = R.drawable.bg,"Deepak", "Android Developer"),
        Employee(img = R.drawable.bg,"Nitish", "Android Developer"),
        Employee(R.drawable.img_1, "James", "QA Engineer"),
        Employee(R.drawable.bg, "Oliver", "Data Scientist"),
        Employee(R.drawable.bg_2, "William", "Security Analyst"),
        Employee(R.drawable.bg, "Henry", "iOS Developer"),
        Employee(R.drawable.bg_2, "Charlie", "Data Scientist"),
        Employee(R.drawable.bg, "Thomas", "UI/UX Designer"),
        Employee(R.drawable.bg_2, "George", "Project Manager"),
        Employee(R.drawable.bg, "Daniel", "Cloud Architect"),
        Employee(R.drawable.bg_2, "Edward", "DevOps Engineer"),
        Employee(R.drawable.bg, "Samuel", "QA Engineer"),
        Employee(R.drawable.bg_2, "Benjamin", "Android Developer"),
        Employee(R.drawable.bg, "Joseph", "Backend Developer"),
        Employee(R.drawable.bg_3, "Arthur", "Full Stack Developer"),
        Employee(R.drawable.bg, "Alexander", "Project Manager"),
        Employee(R.drawable.bg_3, "Michael", "Security Analyst"),
        Employee(R.drawable.bg, "Jacob", "DevOps Engineer"),
        Employee(R.drawable.img_1, "Ethan", "UI/UX Designer"),
        Employee(R.drawable.img_1, "Matthew", "Cloud Architect"),
        Employee(R.drawable.img_1, "Luke", "Full Stack Developer"),
        Employee(R.drawable.bg, "Jack", "Backend Developer"),
        Employee(R.drawable.bg_3, "Harry", "Security Analyst"),
        Employee(R.drawable.bg, "Leo", "Android Developer"),
        Employee(R.drawable.bg_3, "David", "Software Engineer"),
        Employee(R.drawable.bg, "Sebastian", "Product Designer"),
        Employee(R.drawable.bg_3, "Oscar", "Business Analyst"),
        Employee(R.drawable.bg, "Adam", "Cloud Architect"),
        Employee(R.drawable.bg_2, "Nathan", "Project Manager"),
        Employee(R.drawable.bg, "Ryan", "Security Analyst"),
        Employee(R.drawable.img_1, "Joshua", "QA Engineer"),
        Employee(R.drawable.bg, "Liam", "Backend Developer"),
        Employee(R.drawable.img_1, "Jayden", "Software Engineer"),
        Employee(R.drawable.bg, "Noah", "Full Stack Developer"),
        Employee(R.drawable.bg_3, "Logan", "iOS Developer"),
        Employee(R.drawable.bg, "Aaron", "Product Designer"),
        Employee(R.drawable.bg_2, "Mason", "Frontend Developer"),
        Employee(R.drawable.bg, "Harrison", "DevOps Engineer"),
        Employee(R.drawable.bg_2, "Reuben", "Android Developer"),
        Employee(R.drawable.bg, "Toby", "Cloud Architect"),
        Employee(R.drawable.bg_2, "Caleb", "Backend Developer"),
        Employee(R.drawable.bg_3, "Zachary", "UI/UX Designer"),
        Employee(R.drawable.bg_2, "Finn", "QA Engineer"),
        Employee(R.drawable.bg, "Elliot", "Software Engineer"),
        Employee(R.drawable.bg_2, "Owen", "Full Stack Developer"),
        Employee(R.drawable.bg, "Andrew", "DevOps Engineer"),
        Employee(R.drawable.bg_2, "Blake", "Security Analyst"),
        Employee(R.drawable.bg, "Harvey", "iOS Developer"),
        Employee(R.drawable.bg_2, "Eli", "Frontend Developer"),
        Employee(R.drawable.bg, "Connor", "Cloud Architect"),
        Employee(R.drawable.bg_2, "Max", "Software Engineer"),
        Employee(R.drawable.bg, "Jude", "Data Scientist"),
        Employee(R.drawable.bg_3, "Nathaniel", "Product Designer"),
        Employee(R.drawable.bg, "Isaac", "Android Developer"),
        Employee(R.drawable.bg_2, "Freddie", "Frontend Developer"),
        Employee(R.drawable.bg, "Alfie", "Project Manager"),
        Employee(R.drawable.bg_2, "Louis", "Business Analyst"),
        Employee(R.drawable.bg, "Theo", "DevOps Engineer"),
        Employee(R.drawable.bg_3, "Aiden", "Security Analyst"),
        Employee(R.drawable.bg, "Tyler", "Data Scientist"),
        Employee(R.drawable.bg_3, "Archie", "Full Stack Developer"),
        Employee(R.drawable.bg, "Leon", "QA Engineer"),
        Employee(R.drawable.bg_2, "Kai", "Product Designer"),
        Employee(R.drawable.bg, "Ezra", "iOS Developer"),
        Employee(R.drawable.bg_2, "Alex", "Software Engineer"),
        Employee(R.drawable.bg, "Callum", "Backend Developer"),
        Employee(R.drawable.bg_3, "Jenson", "Business Analyst"),
        Employee(R.drawable.bg, "Miles", "Security Analyst"),
        Employee(R.drawable.bg_2, "Rowan", "DevOps Engineer"),
        Employee(R.drawable.bg, "Rory", "Project Manager"),
        Employee(R.drawable.bg_2, "Carter", "Product Designer"),
        Employee(R.drawable.bg, "Brody", "Cloud Architect"),
        Employee(R.drawable.bg_2, "Hunter", "iOS Developer"),
        Employee(R.drawable.bg, "Austin", "Backend Developer"),
        Employee(R.drawable.bg_2, "Grayson", "Android Developer"),
        Employee(R.drawable.bg, "Joel", "UI/UX Designer"),
        Employee(R.drawable.bg_2, "Ellis", "Security Analyst"),
        Employee(R.drawable.bg, "Dominic", "Full Stack Developer"),
        Employee(R.drawable.bg_2, "Spencer", "Business Analyst"),
        Employee(R.drawable.bg, "Angus", "Project Manager"),
        Employee(R.drawable.bg_2, "Cameron", "Software Engineer"),
        Employee(R.drawable.bg, "Xavier", "Cloud Architect"),
        Employee(R.drawable.bg_2, "Cody", "DevOps Engineer"),
        Employee(R.drawable.bg, "Bradley", "Frontend Developer"),
        Employee(R.drawable.bg_2, "Reece", "Backend Developer"),
        Employee(R.drawable.bg, "Kian", "UI/UX Designer"),
        Employee(R.drawable.img_1, "Finley", "Android Developer"),
        Employee(R.drawable.bg, "Arlo", "Security Analyst"),
        Employee(R.drawable.bg_2, "Hudson", "Business Analyst"),
        Employee(R.drawable.img_1, "Luca", "Project Manager"),
        Employee(R.drawable.bg_2, "Evan", "Full Stack Developer"),
        Employee(R.drawable.bg, "Riley", "QA Engineer"),
        Employee(R.drawable.bg_2, "Ronan", "iOS Developer"),
        Employee(R.drawable.bg, "Tristan", "Software Engineer"),
        Employee(R.drawable.bg_2, "Malcolm", "Cloud Architect"),
        Employee(R.drawable.bg, "Declan", "Frontend Developer"),
        Employee(R.drawable.bg_2, "Bryce", "DevOps Engineer"),
        Employee(R.drawable.bg, "Seth", "UI/UX Designer"),
        Employee(R.drawable.bg_2, "Lawson", "Product Designer"),
        Employee(R.drawable.bg, "Corbin", "Android Developer"),
        Employee(R.drawable.bg_2, "Dylan", "Security Analyst"),
        Employee(R.drawable.img_1, "Clayton", "Backend Developer")



    )
}